# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: MFMod JG - The long-term Jobs and Growth version of MFMod
author: Andrew Burns
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: MFMod-JG_UserGuide.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    bibtex_default_style: plain

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - colon_fence


# Information about where the book exists on the web
#repository:
#  url: https://isimulate.worldbank.org/mfm_admin/MFMSA_JG  # Online location of your book
#  path_to_book: \\wbgmisism005\mfm_admin\MFMSA_JG  # Optional path to your book, relative to the repository root
#  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
#html:
#  use_issues_button: true
#  use_repository_button: true
